---
markdown: kramdown
plugins:
  - jekyll-redirect-from
url: https://github.com/googleapis/aip
defaults:
  - scope:
      path: README.md
    values:
      exclude_from_search: true
      js:
        - /assets/js/aip/aip-index.js
tipue_search:
  include:
    pages: true
